version: "3.4"

networks:
  uniting_net:


services:
  db:
    build:
      context: .
      dockerfile: deploy/db.Dockerfile
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - uniting_net
    volumes:
      - ./data:/var/lib/postgresql/data

  auth:
    build:
      context: .
      dockerfile: deploy/auth.Dockerfile
      target: release
    ports:
      - 8092:8092
    restart: always
    networks:
      - uniting_net
    depends_on:
      - db
    command:
      /bin/bash -c "/home/app/auth.out /home/app/config_deploy.json"

  api:
    build:
      context: .
      dockerfile: deploy/api.Dockerfile
      target: release
    ports:
      - 8091:8091
    expose:
      - 8091
    restart: always
    networks:
      - uniting_net
    depends_on:
      - db
      - auth
    command:
      /bin/bash -c "/home/app/wait_for_it.sh -t 600 db:5432 && /home/app/wait_for_it.sh -t 600 auth:8092 && /home/app/api.out /home/app/config_deploy.json"
    volumes:
      - ./upload:/home/app/upload

  nginx:
    build:
      context: .
      dockerfile: deploy/nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    volumes:
      - /etc/ssl:/etc/ssl
    networks:
      - uniting_net
