// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthCookie struct {
	Data                 string   `protobuf:"bytes,1,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=Secret,json=secret,proto3" json:"Secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthCookie) Reset()         { *m = AuthCookie{} }
func (m *AuthCookie) String() string { return proto.CompactTextString(m) }
func (*AuthCookie) ProtoMessage()    {}
func (*AuthCookie) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *AuthCookie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthCookie.Unmarshal(m, b)
}
func (m *AuthCookie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthCookie.Marshal(b, m, deterministic)
}
func (m *AuthCookie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthCookie.Merge(m, src)
}
func (m *AuthCookie) XXX_Size() int {
	return xxx_messageInfo_AuthCookie.Size(m)
}
func (m *AuthCookie) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthCookie.DiscardUnknown(m)
}

var xxx_messageInfo_AuthCookie proto.InternalMessageInfo

func (m *AuthCookie) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *AuthCookie) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type BoolResult struct {
	BoolResult           bool     `protobuf:"varint,1,opt,name=BoolResult,json=boolResult,proto3" json:"BoolResult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolResult) Reset()         { *m = BoolResult{} }
func (m *BoolResult) String() string { return proto.CompactTextString(m) }
func (*BoolResult) ProtoMessage()    {}
func (*BoolResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *BoolResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolResult.Unmarshal(m, b)
}
func (m *BoolResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolResult.Marshal(b, m, deterministic)
}
func (m *BoolResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolResult.Merge(m, src)
}
func (m *BoolResult) XXX_Size() int {
	return xxx_messageInfo_BoolResult.Size(m)
}
func (m *BoolResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolResult.DiscardUnknown(m)
}

var xxx_messageInfo_BoolResult proto.InternalMessageInfo

func (m *BoolResult) GetBoolResult() bool {
	if m != nil {
		return m.BoolResult
	}
	return false
}

type IdResult struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdResult) Reset()         { *m = IdResult{} }
func (m *IdResult) String() string { return proto.CompactTextString(m) }
func (*IdResult) ProtoMessage()    {}
func (*IdResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *IdResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdResult.Unmarshal(m, b)
}
func (m *IdResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdResult.Marshal(b, m, deterministic)
}
func (m *IdResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdResult.Merge(m, src)
}
func (m *IdResult) XXX_Size() int {
	return xxx_messageInfo_IdResult.Size(m)
}
func (m *IdResult) XXX_DiscardUnknown() {
	xxx_messageInfo_IdResult.DiscardUnknown(m)
}

var xxx_messageInfo_IdResult proto.InternalMessageInfo

func (m *IdResult) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthCookie)(nil), "AuthCookie")
	proto.RegisterType((*BoolResult)(nil), "BoolResult")
	proto.RegisterType((*IdResult)(nil), "IdResult")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe0, 0xe2, 0x72, 0x2c, 0x2d, 0xc9, 0x70, 0xce,
	0xcf, 0xcf, 0xce, 0x4c, 0x15, 0x12, 0xe2, 0x62, 0x71, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x14, 0x12, 0xe3, 0x62, 0x0b, 0x4e, 0x4d, 0x2e,
	0x4a, 0x2d, 0x91, 0x60, 0x02, 0x8b, 0xb2, 0x15, 0x83, 0x79, 0x4a, 0x3a, 0x5c, 0x5c, 0x4e, 0xf9,
	0xf9, 0x39, 0x41, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x42, 0x72, 0xc8, 0x3c, 0xb0, 0x7e, 0x8e, 0x20,
	0xae, 0x24, 0xb8, 0x88, 0x92, 0x14, 0x17, 0x87, 0x67, 0x0a, 0x54, 0x2d, 0x1f, 0x17, 0x93, 0x67,
	0x0a, 0x58, 0x0d, 0x73, 0x10, 0x53, 0x66, 0x8a, 0x51, 0x18, 0x17, 0x0b, 0xc8, 0x0d, 0x42, 0xea,
	0x5c, 0x9c, 0x9e, 0xc5, 0x3e, 0xf9, 0xe9, 0x99, 0x79, 0xa9, 0x29, 0x42, 0xdc, 0x7a, 0x08, 0x77,
	0x49, 0x71, 0xeb, 0x21, 0x0c, 0x57, 0x62, 0x10, 0x52, 0xe5, 0xe2, 0x74, 0x4f, 0x2d, 0x09, 0x2d,
	0x4e, 0x2d, 0xf2, 0x44, 0x53, 0xc8, 0xa9, 0x07, 0xb3, 0x45, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x45,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x64, 0x1a, 0x03, 0xf0, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	IsLogined(ctx context.Context, in *AuthCookie, opts ...grpc.CallOption) (*BoolResult, error)
	GetUserId(ctx context.Context, in *AuthCookie, opts ...grpc.CallOption) (*IdResult, error)
}

type authClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthClient(cc grpc.ClientConnInterface) AuthClient {
	return &authClient{cc}
}

func (c *authClient) IsLogined(ctx context.Context, in *AuthCookie, opts ...grpc.CallOption) (*BoolResult, error) {
	out := new(BoolResult)
	err := c.cc.Invoke(ctx, "/Auth/IsLogined", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetUserId(ctx context.Context, in *AuthCookie, opts ...grpc.CallOption) (*IdResult, error) {
	out := new(IdResult)
	err := c.cc.Invoke(ctx, "/Auth/GetUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	IsLogined(context.Context, *AuthCookie) (*BoolResult, error)
	GetUserId(context.Context, *AuthCookie) (*IdResult, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) IsLogined(ctx context.Context, req *AuthCookie) (*BoolResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsLogined not implemented")
}
func (*UnimplementedAuthServer) GetUserId(ctx context.Context, req *AuthCookie) (*IdResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserId not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_IsLogined_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthCookie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).IsLogined(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/IsLogined",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).IsLogined(ctx, req.(*AuthCookie))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthCookie)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auth/GetUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetUserId(ctx, req.(*AuthCookie))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsLogined",
			Handler:    _Auth_IsLogined_Handler,
		},
		{
			MethodName: "GetUserId",
			Handler:    _Auth_GetUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
